### ISSUE TITLE
Data Package Forms messed up (in Firefox)

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/clarity-theme#14] opened 2019-11-08 09:50 UTC
See screenshot below:

![grafik](https://user-images.githubusercontent.com/1788226/68466186-2d401f80-0214-11ea-9992-72c4db119f60.png)

@DenoBeno @patrickkaleta 
Any ideas for a quick (& dirty?) temporary fix of this issue? I don't want to wait weeks for this to be resolved, I have to create screenshots for D4.4. It's probably just one CSS property, but I haven't found out which one yet.

**Comment by patrickkaleta** [comment] 2019-11-08 10:00
Probably caused by latest update of the theme (deployed last Friday).

@p-a-s-c-a-l  which data package exactly are you viewing? I just checked the "European wide DP" ([edit-link](https://csis.myclimateservice.eu/node/682/edit)) and it's being displayed just fine. (viewed on a standard full-HD screen)

![dp-edit-form-messy](https://user-images.githubusercontent.com/42167036/68467558-b35d6580-0216-11ea-9a99-4b21f406acb4.png)

**Comment by p-a-s-c-a-l** [comment] 2019-11-08 11:15
Hm, the [European Wide Data Package](https://csis.myclimateservice.eu/node/682/edit).

OK, switching from Firefox to Chrome it looks better:

![grafik](https://user-images.githubusercontent.com/1788226/68472725-69c64800-0221-11ea-975a-4cc5c21a119f.png)

Thanks.

**Comment by patrickkaleta** [comment] 2019-11-08 12:25
I can confirm that this bug occurs in Firefox (version 64 and also in current version 70).

The problem seems to be caused by the `display: grid` property of the **\<main\>** element. Based on that I'm assuming data package forms might not be the only place, where this error can occur.

I wasn't able to find a quick & dirty solution (other than using a different browser), so @bullz please try to get this fixed in the next theme update.

**Comment by DenoBeno** [comment] 2019-11-18 19:33
Sorry, CSS is not my stuff. I can kind-of read it, but it gets too complex
too fast for my pleasure.

**Comment by p-a-s-c-a-l** [comment] 2020-02-19 10:55
Please close this issue if this has been resolved in the [updated theme](https://github.com/clarity-h2020/clarity-theme/issues/17) or give feedback on the status.

**Comment by patrickkaleta** [comment] 2020-02-21 12:54
Errors shown in the screenshot are not appearing anymore in the latest theme updates.

**Closed as completed by patrickkaleta** 2020-02-21 12:54 UTC
Labels: bug, BB: UI Integration Platform
